spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/cats-api
    username: admin
    password: admin

springdoc:
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

